[package]
name = "epub-builder"
version = "0.0.1-pre"
authors = ["Elisabeth Henry <liz.henry@ouvaton.org>"]
description = "A Rust library for generating EPUB files"
readme = "README.md"
keywords = ["epub"]
repository = "https://github.com/lise-henry/epub/"
documentation = "https://docs.rs/epub"
license = "MPL-2.0"

[lib]
name = "epub_builder"
path = "src/lib.rs"

[dependencies]
error-chain = "0.7"
mustache = "0.8"
lazy_static = "0.2"
chrono = "0.2"
uuid = { version = "0.3", features = ["v4"] }
tempdir = "0.3" # Used by ZipCommand
zip = "0.2" # Used by ZipLibrary
